ingress:
  enabled: true
  hosts:
    - grafana.127.0.0.1.nip.io
  ingressClassName: traefik
  path: /
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  tls:
    - hosts:
        - grafana.127.0.0.1.nip.io
      secretName: grafana-tls
